[package]
name = "day1"
version = "0.1.0"
authors = ["maxkul <kma.memo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.36"
itertools = "0.9.0"
