[package]
name = "day2"
version = "0.1.0"
authors = ["Max Kulish <kma.memo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.37"
peg = "0.6.3"
thiserror = "1.0.23"
